#Jekyll
title:          Total Possession Soccer
name:           Total Possession Soccer
url:
destination:    dist
permalink:      "/:slug/"
year:           2016

#Assets
sass:
    sass_dir:   _sass
    style:      :compressed

#Include
include:        ['_pages']

#Exclude
exclude:        ['node_modules', 'gulpfile.js', 'package.json', '_config.yml', 'js/src/', 'img/src/']
